version: '3.9'

services:
  database:
    image: postgres:14-alpine
    container_name: postgres-database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data:delegated
    healthcheck:
      test: pg_isready -U postgres -h localhost
      interval: 5s
  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=database
    ports:
      - '8080:8080'

volumes:
  database:
    driver: local
